package zeabur

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/ingemar0720/host-from-docker-to-cloud/internal/composeproj"
	"github.com/ingemar0720/host-from-docker-to-cloud/internal/strategy"
)

func TestRender_containsAPIAndHealthDepends(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte(`
name: rendertest
services:
  db:
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
  api:
    image: nginx:alpine
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
`), 0o644))

	p, err := composeproj.Load(context.Background(), dir, []string{"docker-compose.yml"})
	require.NoError(t, err)

	classes := map[string]strategy.Result{}
	for _, n := range p.ServiceNames() {
		classes[n] = strategy.Classify(strategy.File{}, n, p.Services[n])
	}

	var buf bytes.Buffer
	require.NoError(t, Render(context.Background(), &buf, p, classes))
	out := buf.String()

	require.Contains(t, out, "apiVersion: zeabur.com/v1")
	require.Contains(t, out, "kind: Project")
	require.Contains(t, out, `name: db`)
	require.Contains(t, out, `name: api`)
	require.Contains(t, out, "service_healthy")
	require.Contains(t, out, "CMD-SHELL")
	require.Contains(t, out, "Generated by d2z")
}

func TestRender_deploymentOrder_dbBeforeAPI(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte(`
name: ord
services:
  api:
    image: nginx:alpine
    depends_on:
      - db
  db:
    image: postgres:16-alpine
`), 0o644))

	p, err := composeproj.Load(context.Background(), dir, []string{"docker-compose.yml"})
	require.NoError(t, err)
	classes := map[string]strategy.Result{}
	for _, n := range p.ServiceNames() {
		classes[n] = strategy.Classify(strategy.File{}, n, p.Services[n])
	}

	var buf bytes.Buffer
	require.NoError(t, Render(context.Background(), &buf, p, classes))
	out := buf.String()

	idxDB := bytes.Index([]byte(out), []byte("name: db"))
	idxAPI := bytes.Index([]byte(out), []byte("name: api"))
	require.NotEqual(t, -1, idxDB)
	require.NotEqual(t, -1, idxAPI)
	require.Less(t, idxDB, idxAPI)
}
