package zeabur

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/compose-spec/compose-go/v2/types"
	"gopkg.in/yaml.v3"

	"github.com/ingemar0720/host-from-docker-to-cloud/internal/strategy"
)

// Document is a best-effort Zeabur-oriented template. Confirm against current Zeabur docs before applying.
type Document struct {
	APIVersion string          `yaml:"apiVersion"`
	Kind       string          `yaml:"kind"`
	Metadata   Metadata        `yaml:"metadata"`
	Spec       ProjectSpec     `yaml:"spec"`
	Comments   []string        `yaml:"-"`
}

type Metadata struct {
	Name string `yaml:"name"`
}

type ProjectSpec struct {
	Services []ServiceSpec `yaml:"services"`
}

type ServiceSpec struct {
	Name            string            `yaml:"name"`
	Classification  string            `yaml:"classification,omitempty"`
	Image           string            `yaml:"image,omitempty"`
	Build           *BuildSpec        `yaml:"build,omitempty"`
	Environment     map[string]string `yaml:"environment,omitempty"`
	Ports           []PortSpec        `yaml:"ports,omitempty"`
	DependsOn       []DepEdge         `yaml:"dependsOn,omitempty"`
	Healthcheck     *HealthSpec       `yaml:"healthcheck,omitempty"`
	DeploymentOrder int               `yaml:"deploymentOrder,omitempty"`
	Notes           []string          `yaml:"notes,omitempty"`
}

type BuildSpec struct {
	Context    string            `yaml:"context,omitempty"`
	Dockerfile string            `yaml:"dockerfile,omitempty"`
	Args       map[string]string `yaml:"args,omitempty"`
}

type PortSpec struct {
	Target    uint32 `yaml:"target"`
	Published string `yaml:"published,omitempty"`
	Protocol  string `yaml:"protocol,omitempty"`
}

type DepEdge struct {
	Service   string `yaml:"service"`
	Condition string `yaml:"condition"`
	Required  bool   `yaml:"required"`
}

type HealthSpec struct {
	Test        []string `yaml:"test,omitempty"`
	Interval    string   `yaml:"interval,omitempty"`
	Timeout     string   `yaml:"timeout,omitempty"`
	Retries     *uint64  `yaml:"retries,omitempty"`
	StartPeriod string   `yaml:"start_period,omitempty"`
	Disable     bool     `yaml:"disable,omitempty"`
}

// Render writes a YAML document derived from the project and strategy classification.
func Render(ctx context.Context, out io.Writer, project *types.Project, classes map[string]strategy.Result) error {
	order, err := dependencyOrder(ctx, project)
	if err != nil {
		return err
	}
	orderRank := map[string]int{}
	for i, n := range order {
		orderRank[n] = i
	}

	doc := Document{
		APIVersion: "zeabur.com/v1",
		Kind:       "Project",
		Metadata:   Metadata{Name: project.Name},
		Spec:       ProjectSpec{Services: nil},
		Comments: []string{
			"Generated by d2z — verify fields against https://zeabur.com/docs before deploy.",
			"dependency order follows Compose depends_on; conditions mirror service_healthy / service_started / service_completed_successfully.",
		},
	}

	names := project.ServiceNames()
	for _, name := range names {
		svc := project.Services[name]
		cl := classes[name]
		ss := ServiceSpec{
			Name:           name,
			Classification: string(cl.Kind),
			Image:          svc.Image,
			Environment:    envToMap(svc.Environment),
			DeploymentOrder: orderRank[name],
		}
		if svc.Build != nil {
			ss.Build = &BuildSpec{
				Context:    svc.Build.Context,
				Dockerfile: svc.Build.Dockerfile,
				Args:       stringMapFrom(svc.Build.Args),
			}
		}
		for _, p := range svc.Ports {
			ss.Ports = append(ss.Ports, PortSpec{
				Target:    p.Target,
				Published: p.Published,
				Protocol:  p.Protocol,
			})
		}
		for dep, d := range svc.DependsOn {
			cond := strings.TrimSpace(d.Condition)
			if cond == "" {
				cond = types.ServiceConditionStarted
			}
			ss.DependsOn = append(ss.DependsOn, DepEdge{
				Service:   dep,
				Condition: cond,
				Required:  d.Required,
			})
		}
		sort.Slice(ss.DependsOn, func(i, j int) bool { return ss.DependsOn[i].Service < ss.DependsOn[j].Service })

		if svc.HealthCheck != nil && !svc.HealthCheck.Disable {
			ss.Healthcheck = healthToSpec(svc.HealthCheck)
		}
		ss.Notes = deploymentNotes(svc, cl)
		doc.Spec.Services = append(doc.Spec.Services, ss)
	}
	sort.Slice(doc.Spec.Services, func(i, j int) bool {
		return doc.Spec.Services[i].DeploymentOrder < doc.Spec.Services[j].DeploymentOrder
	})

	enc := yaml.NewEncoder(out)
	enc.SetIndent(2)
	defer enc.Close()
	for _, c := range doc.Comments {
		if _, err := fmt.Fprintf(out, "# %s\n", c); err != nil {
			return err
		}
	}
	return enc.Encode(doc)
}

func deploymentNotes(svc types.ServiceConfig, cl strategy.Result) []string {
	var n []string
	n = append(n, "strategy: "+cl.Reason)
	if len(svc.Secrets) > 0 {
		n = append(n, "Compose secrets: map to Bitwarden Secrets Manager or Zeabur env (see PLAN.md §8).")
	}
	if cl.Kind == strategy.PrivateBuildECR || cl.Kind == strategy.PrivateImage {
		n = append(n, "Private path: configure ECR + Zeabur registry credentials; use make push-ecr where applicable.")
	}
	return n
}

func dependencyOrder(ctx context.Context, project *types.Project) ([]string, error) {
	_ = ctx // reserved for future cancellation-aware planners

	names := project.ServiceNames()
	sort.Strings(names)

	indegree := make(map[string]int, len(names))
	dependents := make(map[string][]string, len(names))
	for _, name := range names {
		indegree[name] = 0
	}

	for _, name := range names {
		svc := project.Services[name]
		deps := make([]string, 0, len(svc.DependsOn))
		for dep := range svc.DependsOn {
			deps = append(deps, dep)
		}
		sort.Strings(deps)
		for _, dep := range deps {
			if _, ok := indegree[dep]; !ok {
				continue
			}
			indegree[name]++
			dependents[dep] = append(dependents[dep], name)
		}
	}

	ready := make([]string, 0, len(names))
	for _, name := range names {
		if indegree[name] == 0 {
			ready = append(ready, name)
		}
	}
	sort.Strings(ready)

	order := make([]string, 0, len(names))
	for len(ready) > 0 {
		name := ready[0]
		ready = ready[1:]
		order = append(order, name)

		ds := dependents[name]
		sort.Strings(ds)
		for _, d := range ds {
			indegree[d]--
			if indegree[d] == 0 {
				i := sort.SearchStrings(ready, d)
				ready = append(ready, "")
				copy(ready[i+1:], ready[i:])
				ready[i] = d
			}
		}
	}

	if len(order) != len(names) {
		return nil, fmt.Errorf("dependency planner: cycle detected in services")
	}
	return order, nil
}

func envToMap(e types.MappingWithEquals) map[string]string {
	if len(e) == 0 {
		return nil
	}
	out := map[string]string{}
	for k, v := range e {
		if v == nil {
			continue
		}
		out[k] = *v
	}
	return out
}

func stringMapFrom(m map[string]*string) map[string]string {
	if len(m) == 0 {
		return nil
	}
	out := map[string]string{}
	for k, v := range m {
		if v != nil {
			out[k] = *v
		}
	}
	return out
}

func healthToSpec(h *types.HealthCheckConfig) *HealthSpec {
	if h == nil {
		return nil
	}
	hs := &HealthSpec{
		Test:    append([]string(nil), h.Test...),
		Disable: h.Disable,
	}
	if h.Interval != nil {
		hs.Interval = h.Interval.String()
	}
	if h.Timeout != nil {
		hs.Timeout = h.Timeout.String()
	}
	if h.StartPeriod != nil {
		hs.StartPeriod = h.StartPeriod.String()
	}
	if h.Retries != nil {
		hs.Retries = h.Retries
	}
	return hs
}
